#!/usr/bin/env bash
#
# CompDesk in-container setup (Debian 12). Idempotent: safe to re-run.
# Executed by install/compdesk.sh inside the LXC container as root.
set -euo pipefail

APP="${APP:-compdesk}"
APP_DIR="${APP_DIR:-/opt/compdesk}"
ENV_DIR="${ENV_DIR:-/var/lib/compdesk}"
ENV_FILE="${ENV_DIR}/.env"
APP_USER="${APP_USER:-compdesk}"
DB_NAME="${DB_NAME:-compdesk_db}"
DB_USER="${DB_USER:-compdesk}"
APP_PORT="${APP_PORT:-3000}"
REPO_URL="${REPO_URL:-https://github.com/HatchetMan111/CompDeskTicketingSystem.git}"
BRANCH="${BRANCH:-main}"
RAW_BASE="${RAW_BASE:-https://raw.githubusercontent.com/HatchetMan111/CompDeskTicketingSystem/main}"
DEBUG="${DEBUG:-0}"

export DEBIAN_FRONTEND=noninteractive
LOG="/tmp/${APP}-in-ct-$(date +%Y%m%d-%H%M%S).log"

if [ "$DEBUG" = "1" ]; then
  set -x
fi

err() {
  local code=$?
  set +x
  echo "" >&2
  echo "================ IN-CONTAINER SETUP FAILED ================" >&2
  echo "Failed command : ${BASH_COMMAND}" >&2
  echo "Exit code      : ${code}" >&2
  echo "--- call stack (most recent first) ---" >&2
  local i=0
  while caller "$i" >&2; do
    i=$((i + 1))
  done
  echo "--- systemctl compdesk ---" >&2
  systemctl status compdesk --no-pager >&2 || true
  echo "--- journal compdesk (last 50) ---" >&2
  journalctl -u compdesk -n 50 --no-pager >&2 || true
  echo "--- pg_isready ---" >&2
  pg_isready >&2 || true
  echo "--- full log: ${LOG} ---" >&2
  echo "Re-run with: DEBUG=1 bash -x /tmp/compdesk-install.sh" >&2
  exit "$code"
}
trap err ERR

msg() { echo "==> $*"; }

install_base() {
  msg "Installing base packages..."
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates curl git gnupg openssl sudo wget \
    postgresql-client
}

install_node() {
  if command -v node >/dev/null 2>&1 && node --version | grep -q "^v24\."; then
    msg "Node 24 already present: $(node --version)"
    return 0
  fi
  msg "Installing Node.js 24 (NodeSource)..."
  mkdir -p /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
    | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_24.x nodistro main" \
    > /etc/apt/sources.list.d/nodesource.list
  apt-get update
  apt-get install -y --no-install-recommends nodejs
  node --version
}

install_postgres() {
  if pg_lsclusters 2>/dev/null | grep -q "^16 "; then
    msg "PostgreSQL 16 cluster already present."
  else
    msg "Installing PostgreSQL 16 (PGDG)..."
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
      | gpg --dearmor -o /etc/apt/keyrings/postgresql.gpg
    echo "deb [signed-by=/etc/apt/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" \
      > /etc/apt/sources.list.d/pgdg.list
    apt-get update
    apt-get install -y --no-install-recommends postgresql-16
  fi
  systemctl enable --now postgresql
  pg_isready
}

ensure_app_user() {
  if ! id -u "$APP_USER" >/dev/null 2>&1; then
    msg "Creating user ${APP_USER}..."
    useradd -r -m -s /bin/bash "$APP_USER"
  fi
}

ensure_env_file() {
  mkdir -p "$ENV_DIR"
  local ct_ip
  ct_ip="$(hostname -I | awk '{print $1}')"
  local db_pw="" auth_secret="" settings_key=""
  if [ -f "$ENV_FILE" ]; then
    msg "Reusing existing ${ENV_FILE} (secrets are never rotated)."
    # shellcheck disable=SC1090
    set +u; source "$ENV_FILE"; set -u
    db_pw="${POSTGRES_PASSWORD:-}"
    auth_secret="${AUTH_SECRET:-}"
    settings_key="${APP_SETTINGS_ENCRYPTION_KEY:-}"
  fi
  [ -n "$db_pw" ] || db_pw="$(openssl rand -hex 24)"
  [ -n "$auth_secret" ] || auth_secret="$(openssl rand -base64 32)"
  [ -n "$settings_key" ] || settings_key="$(openssl rand -base64 32)"
  cat > "$ENV_FILE" <<EOF
# Generated by compdesk-install.sh. Do not log or share this file.
DATABASE_URL="postgresql://${DB_USER}:${db_pw}@127.0.0.1:5432/${DB_NAME}"
POSTGRES_PASSWORD="${db_pw}"
AUTH_URL="http://${ct_ip}:${APP_PORT}"
AUTH_SECRET="${auth_secret}"
APP_SETTINGS_ENCRYPTION_KEY="${settings_key}"
NODE_ENV="production"
PORT="${APP_PORT}"
HOSTNAME="0.0.0.0"
# Allow the first-run setup wizard to bind 0.0.0.0 (same as upstream Docker
# setup). Home LAN only: never expose the setup listener to the Internet.
# The wizard uses a one-time 30-min token and disables itself after install.
SETUP_ALLOW_REMOTE="true"
EOF
  chown root:"$APP_USER" "$ENV_FILE"
  chmod 640 "$ENV_FILE"
  msg "Wrote ${ENV_FILE} (0600-equivalent, group ${APP_USER} read)."
}

ensure_database() {
  msg "Ensuring PostgreSQL role/database..."
  # shellcheck disable=SC1090
  set +u; source "$ENV_FILE"; set -u
  su - postgres -c "psql -v ON_ERROR_STOP=1 -c \"DO \\\$\\\$BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN CREATE ROLE ${DB_USER} LOGIN PASSWORD '${POSTGRES_PASSWORD}'; ELSE ALTER ROLE ${DB_USER} LOGIN PASSWORD '${POSTGRES_PASSWORD}'; END IF; END \\\$\\\$;\""
  su - postgres -c "psql -v ON_ERROR_STOP=1 -tAc \"SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'\" | grep -q 1 || createdb -O ${DB_USER} ${DB_NAME}"
  PGPASSWORD="$POSTGRES_PASSWORD" pg_isready -h 127.0.0.1 -U "$DB_USER" -d "$DB_NAME"
}

sync_code() {
  if [ -d "${APP_DIR}/.git" ]; then
    msg "Updating ${APP_DIR} (${BRANCH})..."
    git -C "$APP_DIR" fetch origin
    git -C "$APP_DIR" checkout "$BRANCH"
    git -C "$APP_DIR" pull --ff-only origin "$BRANCH"
  else
    msg "Cloning ${REPO_URL} (${BRANCH}) into ${APP_DIR}..."
    git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$APP_DIR"
  fi
  chown -R "$APP_USER":"$APP_USER" "$APP_DIR"
}

build_app() {
  msg "Installing npm dependencies (may take several minutes)..."
  # shellcheck disable=SC1090
  set +u; source "$ENV_FILE"; set -u
  sudo -u "$APP_USER" env DATABASE_URL="$DATABASE_URL" bash -c "cd '$APP_DIR' && npm ci"
  msg "Generating Prisma client + running migrations..."
  sudo -u "$APP_USER" env DATABASE_URL="$DATABASE_URL" bash -c "cd '$APP_DIR' && npx prisma generate && npx prisma migrate deploy"
  msg "Building Next.js standalone..."
  sudo -u "$APP_USER" env DATABASE_URL="$DATABASE_URL" AUTH_URL="$AUTH_URL" AUTH_SECRET="$AUTH_SECRET" bash -c "cd '$APP_DIR' && npm run build"
}

install_service() {
  msg "Installing systemd unit..."
  wget -qO /etc/systemd/system/compdesk.service "${RAW_BASE}/deploy/compdesk.service"
  # Allow ATTACHMENT_STORAGE_DIR default (relative) to resolve under /opt/compdesk:
  mkdir -p "${APP_DIR}/storage/attachments"
  chown -R "$APP_USER":"$APP_USER" "${APP_DIR}/storage"
  systemctl daemon-reload
  systemctl enable --now compdesk
}

open_firewall_port() {
  if command -v iptables >/dev/null 2>&1; then
    if ! iptables -C INPUT -p tcp --dport "$APP_PORT" -j ACCEPT 2>/dev/null; then
      iptables -A INPUT -p tcp --dport "$APP_PORT" -j ACCEPT || true
      msg "Opened TCP/${APP_PORT} in iptables (best effort)."
    fi
  fi
}

verify() {
  msg "Verifying services..."
  systemctl is-active --quiet compdesk
  systemctl is-active --quiet postgresql
  msg "Waiting for Web UI (up to 150s)..."
  local i
  for i in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:${APP_PORT}/api/health/live" >/dev/null 2>&1; then
      msg "Web UI health check OK."
      return 0
    fi
    sleep 5
  done
  echo "ERROR: Web UI did not answer within 150s." >&2
  exit 6
}

main() {
  exec > >(tee -a "$LOG") 2>&1
  msg "CompDesk in-container setup (log: ${LOG})"
  install_base
  install_node
  install_postgres
  ensure_app_user
  ensure_env_file
  ensure_database
  sync_code
  build_app
  install_service
  open_firewall_port
  verify
  msg "In-container setup complete."
}

main "$@"
